blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/Warriorlegacy/Signhify_CLI/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/Warriorlegacy/Signhify_CLI/security/advisories
    about: Please report security vulnerabilities here.
